name: "Coding Standards"
env:
  APP_ENV: test

on: [push, pull_request]

jobs:
  coding-standards:
    name: "Coding Standards"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.4"
          - "8.3"
          - "8.2"
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: "Run composer normalize"
        run: "composer normalize --diff --dry-run"

      - name: "Run php cs fixer"
        run: "PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer fix --diff --dry-run --using-cache=no"
