name: "Static analysing"
env:
  APP_ENV: test

on: [push, pull_request]

jobs:
  coding-standards:
    name: "Static analysing"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.4"
          - "8.3"
          - "8.2"
          - "8.1"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"

      - name: "Run phpstan"
        run: "vendor/bin/phpstan"
